services:
  - type: web
    name: voxaroid-vanilla-frontend
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    envVars:
      - key: BACKEND_URL
        value: https://your-server-py-domain.onrender.com
      - key: LEMONSQUEEZY_STORE_ID
        value: your_lemonsqueezy_store_id
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
